/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './modules/routing/__root'
import { Route as VerifyOtpRouteImport } from './modules/routing/verify-otp'
import { Route as SoldeRouteImport } from './modules/routing/solde'
import { Route as SignupRouteImport } from './modules/routing/signup'
import { Route as ResetPasswordRouteImport } from './modules/routing/reset-password'
import { Route as ProfilRouteImport } from './modules/routing/profil'
import { Route as PlanifierRouteImport } from './modules/routing/planifier'
import { Route as ParametresRouteImport } from './modules/routing/parametres'
import { Route as LoginRouteImport } from './modules/routing/login'
import { Route as LandingRouteImport } from './modules/routing/landing'
import { Route as HistoriqueRouteImport } from './modules/routing/historique'
import { Route as ForgotPasswordRouteImport } from './modules/routing/forgot-password'
import { Route as DemandesRouteImport } from './modules/routing/demandes'
import { Route as DeclarerRouteImport } from './modules/routing/declarer'
import { Route as AdminLoginRouteImport } from './modules/routing/admin-login'
import { Route as IndexRouteImport } from './modules/routing/index'
import { Route as RhIndexRouteImport } from './modules/routing/rh.index'
import { Route as ManagerIndexRouteImport } from './modules/routing/manager.index'
import { Route as RhSpeciauxRouteImport } from './modules/routing/rh.speciaux'
import { Route as RhSoldesCpRouteImport } from './modules/routing/rh.soldes-cp'
import { Route as RhProfilRouteImport } from './modules/routing/rh.profil'
import { Route as RhPassifRouteImport } from './modules/routing/rh.passif'
import { Route as RhParametresRouteImport } from './modules/routing/rh.parametres'
import { Route as RhHierarchieRouteImport } from './modules/routing/rh.hierarchie'
import { Route as RhGlobalRouteImport } from './modules/routing/rh.global'
import { Route as RhExportsRouteImport } from './modules/routing/rh.exports'
import { Route as RhEnfantsRouteImport } from './modules/routing/rh.enfants'
import { Route as RhEmployesRouteImport } from './modules/routing/rh.employes'
import { Route as RhDemandesCongesRouteImport } from './modules/routing/rh.demandes-conges'
import { Route as RhAuditRouteImport } from './modules/routing/rh.audit'
import { Route as RhAlertesRouteImport } from './modules/routing/rh.alertes'
import { Route as ManagerProfilRouteImport } from './modules/routing/manager.profil'
import { Route as ManagerPlanningRouteImport } from './modules/routing/manager.planning'
import { Route as ManagerParametresRouteImport } from './modules/routing/manager.parametres'
import { Route as ManagerHistoriqueRouteImport } from './modules/routing/manager.historique'
import { Route as ManagerDemandesRouteImport } from './modules/routing/manager.demandes'
import { Route as ManagerConflitsRouteImport } from './modules/routing/manager.conflits'
import { Route as ManagerCalendrierRouteImport } from './modules/routing/manager.calendrier'
import { Route as AdminWorkflowsRouteImport } from './modules/routing/admin.workflows'
import { Route as AdminUsersRouteImport } from './modules/routing/admin.users'
import { Route as AdminRolesRouteImport } from './modules/routing/admin.roles'
import { Route as AdminProfilRouteImport } from './modules/routing/admin.profil'
import { Route as AdminParametresRouteImport } from './modules/routing/admin.parametres'
import { Route as AdminLogsRouteImport } from './modules/routing/admin.logs'
import { Route as AdminFeriesRouteImport } from './modules/routing/admin.feries'
import { Route as AdminDepartementsRouteImport } from './modules/routing/admin.departements'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldeRoute = SoldeRouteImport.update({
  id: '/solde',
  path: '/solde',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanifierRoute = PlanifierRouteImport.update({
  id: '/planifier',
  path: '/planifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesRoute = DemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclarerRoute = DeclarerRouteImport.update({
  id: '/declarer',
  path: '/declarer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/rh/',
  path: '/rh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhSpeciauxRoute = RhSpeciauxRouteImport.update({
  id: '/rh/speciaux',
  path: '/rh/speciaux',
  getParentRoute: () => rootRouteImport,
} as any)
const RhSoldesCpRoute = RhSoldesCpRouteImport.update({
  id: '/rh/soldes-cp',
  path: '/rh/soldes-cp',
  getParentRoute: () => rootRouteImport,
} as any)
const RhProfilRoute = RhProfilRouteImport.update({
  id: '/rh/profil',
  path: '/rh/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RhPassifRoute = RhPassifRouteImport.update({
  id: '/rh/passif',
  path: '/rh/passif',
  getParentRoute: () => rootRouteImport,
} as any)
const RhParametresRoute = RhParametresRouteImport.update({
  id: '/rh/parametres',
  path: '/rh/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RhHierarchieRoute = RhHierarchieRouteImport.update({
  id: '/rh/hierarchie',
  path: '/rh/hierarchie',
  getParentRoute: () => rootRouteImport,
} as any)
const RhGlobalRoute = RhGlobalRouteImport.update({
  id: '/rh/global',
  path: '/rh/global',
  getParentRoute: () => rootRouteImport,
} as any)
const RhExportsRoute = RhExportsRouteImport.update({
  id: '/rh/exports',
  path: '/rh/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const RhEnfantsRoute = RhEnfantsRouteImport.update({
  id: '/rh/enfants',
  path: '/rh/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const RhEmployesRoute = RhEmployesRouteImport.update({
  id: '/rh/employes',
  path: '/rh/employes',
  getParentRoute: () => rootRouteImport,
} as any)
const RhDemandesCongesRoute = RhDemandesCongesRouteImport.update({
  id: '/rh/demandes-conges',
  path: '/rh/demandes-conges',
  getParentRoute: () => rootRouteImport,
} as any)
const RhAuditRoute = RhAuditRouteImport.update({
  id: '/rh/audit',
  path: '/rh/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const RhAlertesRoute = RhAlertesRouteImport.update({
  id: '/rh/alertes',
  path: '/rh/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerProfilRoute = ManagerProfilRouteImport.update({
  id: '/manager/profil',
  path: '/manager/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerPlanningRoute = ManagerPlanningRouteImport.update({
  id: '/manager/planning',
  path: '/manager/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerParametresRoute = ManagerParametresRouteImport.update({
  id: '/manager/parametres',
  path: '/manager/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerHistoriqueRoute = ManagerHistoriqueRouteImport.update({
  id: '/manager/historique',
  path: '/manager/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDemandesRoute = ManagerDemandesRouteImport.update({
  id: '/manager/demandes',
  path: '/manager/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerConflitsRoute = ManagerConflitsRouteImport.update({
  id: '/manager/conflits',
  path: '/manager/conflits',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCalendrierRoute = ManagerCalendrierRouteImport.update({
  id: '/manager/calendrier',
  path: '/manager/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/admin/workflows',
  path: '/admin/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/admin/profil',
  path: '/admin/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeriesRoute = AdminFeriesRouteImport.update({
  id: '/admin/feries',
  path: '/admin/feries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartementsRoute = AdminDepartementsRouteImport.update({
  id: '/admin/departements',
  path: '/admin/departements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/declarer': typeof DeclarerRoute
  '/demandes': typeof DemandesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historique': typeof HistoriqueRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/planifier': typeof PlanifierRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solde': typeof SoldeRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/departements': typeof AdminDepartementsRoute
  '/admin/feries': typeof AdminFeriesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/manager/calendrier': typeof ManagerCalendrierRoute
  '/manager/conflits': typeof ManagerConflitsRoute
  '/manager/demandes': typeof ManagerDemandesRoute
  '/manager/historique': typeof ManagerHistoriqueRoute
  '/manager/parametres': typeof ManagerParametresRoute
  '/manager/planning': typeof ManagerPlanningRoute
  '/manager/profil': typeof ManagerProfilRoute
  '/rh/alertes': typeof RhAlertesRoute
  '/rh/audit': typeof RhAuditRoute
  '/rh/demandes-conges': typeof RhDemandesCongesRoute
  '/rh/employes': typeof RhEmployesRoute
  '/rh/enfants': typeof RhEnfantsRoute
  '/rh/exports': typeof RhExportsRoute
  '/rh/global': typeof RhGlobalRoute
  '/rh/hierarchie': typeof RhHierarchieRoute
  '/rh/parametres': typeof RhParametresRoute
  '/rh/passif': typeof RhPassifRoute
  '/rh/profil': typeof RhProfilRoute
  '/rh/soldes-cp': typeof RhSoldesCpRoute
  '/rh/speciaux': typeof RhSpeciauxRoute
  '/manager/': typeof ManagerIndexRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/declarer': typeof DeclarerRoute
  '/demandes': typeof DemandesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historique': typeof HistoriqueRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/planifier': typeof PlanifierRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solde': typeof SoldeRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/departements': typeof AdminDepartementsRoute
  '/admin/feries': typeof AdminFeriesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/manager/calendrier': typeof ManagerCalendrierRoute
  '/manager/conflits': typeof ManagerConflitsRoute
  '/manager/demandes': typeof ManagerDemandesRoute
  '/manager/historique': typeof ManagerHistoriqueRoute
  '/manager/parametres': typeof ManagerParametresRoute
  '/manager/planning': typeof ManagerPlanningRoute
  '/manager/profil': typeof ManagerProfilRoute
  '/rh/alertes': typeof RhAlertesRoute
  '/rh/audit': typeof RhAuditRoute
  '/rh/demandes-conges': typeof RhDemandesCongesRoute
  '/rh/employes': typeof RhEmployesRoute
  '/rh/enfants': typeof RhEnfantsRoute
  '/rh/exports': typeof RhExportsRoute
  '/rh/global': typeof RhGlobalRoute
  '/rh/hierarchie': typeof RhHierarchieRoute
  '/rh/parametres': typeof RhParametresRoute
  '/rh/passif': typeof RhPassifRoute
  '/rh/profil': typeof RhProfilRoute
  '/rh/soldes-cp': typeof RhSoldesCpRoute
  '/rh/speciaux': typeof RhSpeciauxRoute
  '/manager': typeof ManagerIndexRoute
  '/rh': typeof RhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/declarer': typeof DeclarerRoute
  '/demandes': typeof DemandesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historique': typeof HistoriqueRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/planifier': typeof PlanifierRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/solde': typeof SoldeRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/departements': typeof AdminDepartementsRoute
  '/admin/feries': typeof AdminFeriesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/manager/calendrier': typeof ManagerCalendrierRoute
  '/manager/conflits': typeof ManagerConflitsRoute
  '/manager/demandes': typeof ManagerDemandesRoute
  '/manager/historique': typeof ManagerHistoriqueRoute
  '/manager/parametres': typeof ManagerParametresRoute
  '/manager/planning': typeof ManagerPlanningRoute
  '/manager/profil': typeof ManagerProfilRoute
  '/rh/alertes': typeof RhAlertesRoute
  '/rh/audit': typeof RhAuditRoute
  '/rh/demandes-conges': typeof RhDemandesCongesRoute
  '/rh/employes': typeof RhEmployesRoute
  '/rh/enfants': typeof RhEnfantsRoute
  '/rh/exports': typeof RhExportsRoute
  '/rh/global': typeof RhGlobalRoute
  '/rh/hierarchie': typeof RhHierarchieRoute
  '/rh/parametres': typeof RhParametresRoute
  '/rh/passif': typeof RhPassifRoute
  '/rh/profil': typeof RhProfilRoute
  '/rh/soldes-cp': typeof RhSoldesCpRoute
  '/rh/speciaux': typeof RhSpeciauxRoute
  '/manager/': typeof ManagerIndexRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/declarer'
    | '/demandes'
    | '/forgot-password'
    | '/historique'
    | '/landing'
    | '/login'
    | '/parametres'
    | '/planifier'
    | '/profil'
    | '/reset-password'
    | '/signup'
    | '/solde'
    | '/verify-otp'
    | '/admin/departements'
    | '/admin/feries'
    | '/admin/logs'
    | '/admin/parametres'
    | '/admin/profil'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workflows'
    | '/manager/calendrier'
    | '/manager/conflits'
    | '/manager/demandes'
    | '/manager/historique'
    | '/manager/parametres'
    | '/manager/planning'
    | '/manager/profil'
    | '/rh/alertes'
    | '/rh/audit'
    | '/rh/demandes-conges'
    | '/rh/employes'
    | '/rh/enfants'
    | '/rh/exports'
    | '/rh/global'
    | '/rh/hierarchie'
    | '/rh/parametres'
    | '/rh/passif'
    | '/rh/profil'
    | '/rh/soldes-cp'
    | '/rh/speciaux'
    | '/manager/'
    | '/rh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/declarer'
    | '/demandes'
    | '/forgot-password'
    | '/historique'
    | '/landing'
    | '/login'
    | '/parametres'
    | '/planifier'
    | '/profil'
    | '/reset-password'
    | '/signup'
    | '/solde'
    | '/verify-otp'
    | '/admin/departements'
    | '/admin/feries'
    | '/admin/logs'
    | '/admin/parametres'
    | '/admin/profil'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workflows'
    | '/manager/calendrier'
    | '/manager/conflits'
    | '/manager/demandes'
    | '/manager/historique'
    | '/manager/parametres'
    | '/manager/planning'
    | '/manager/profil'
    | '/rh/alertes'
    | '/rh/audit'
    | '/rh/demandes-conges'
    | '/rh/employes'
    | '/rh/enfants'
    | '/rh/exports'
    | '/rh/global'
    | '/rh/hierarchie'
    | '/rh/parametres'
    | '/rh/passif'
    | '/rh/profil'
    | '/rh/soldes-cp'
    | '/rh/speciaux'
    | '/manager'
    | '/rh'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/declarer'
    | '/demandes'
    | '/forgot-password'
    | '/historique'
    | '/landing'
    | '/login'
    | '/parametres'
    | '/planifier'
    | '/profil'
    | '/reset-password'
    | '/signup'
    | '/solde'
    | '/verify-otp'
    | '/admin/departements'
    | '/admin/feries'
    | '/admin/logs'
    | '/admin/parametres'
    | '/admin/profil'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/workflows'
    | '/manager/calendrier'
    | '/manager/conflits'
    | '/manager/demandes'
    | '/manager/historique'
    | '/manager/parametres'
    | '/manager/planning'
    | '/manager/profil'
    | '/rh/alertes'
    | '/rh/audit'
    | '/rh/demandes-conges'
    | '/rh/employes'
    | '/rh/enfants'
    | '/rh/exports'
    | '/rh/global'
    | '/rh/hierarchie'
    | '/rh/parametres'
    | '/rh/passif'
    | '/rh/profil'
    | '/rh/soldes-cp'
    | '/rh/speciaux'
    | '/manager/'
    | '/rh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DeclarerRoute: typeof DeclarerRoute
  DemandesRoute: typeof DemandesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoriqueRoute: typeof HistoriqueRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  PlanifierRoute: typeof PlanifierRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SoldeRoute: typeof SoldeRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AdminDepartementsRoute: typeof AdminDepartementsRoute
  AdminFeriesRoute: typeof AdminFeriesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  ManagerCalendrierRoute: typeof ManagerCalendrierRoute
  ManagerConflitsRoute: typeof ManagerConflitsRoute
  ManagerDemandesRoute: typeof ManagerDemandesRoute
  ManagerHistoriqueRoute: typeof ManagerHistoriqueRoute
  ManagerParametresRoute: typeof ManagerParametresRoute
  ManagerPlanningRoute: typeof ManagerPlanningRoute
  ManagerProfilRoute: typeof ManagerProfilRoute
  RhAlertesRoute: typeof RhAlertesRoute
  RhAuditRoute: typeof RhAuditRoute
  RhDemandesCongesRoute: typeof RhDemandesCongesRoute
  RhEmployesRoute: typeof RhEmployesRoute
  RhEnfantsRoute: typeof RhEnfantsRoute
  RhExportsRoute: typeof RhExportsRoute
  RhGlobalRoute: typeof RhGlobalRoute
  RhHierarchieRoute: typeof RhHierarchieRoute
  RhParametresRoute: typeof RhParametresRoute
  RhPassifRoute: typeof RhPassifRoute
  RhProfilRoute: typeof RhProfilRoute
  RhSoldesCpRoute: typeof RhSoldesCpRoute
  RhSpeciauxRoute: typeof RhSpeciauxRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  RhIndexRoute: typeof RhIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solde': {
      id: '/solde'
      path: '/solde'
      fullPath: '/solde'
      preLoaderRoute: typeof SoldeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planifier': {
      id: '/planifier'
      path: '/planifier'
      fullPath: '/planifier'
      preLoaderRoute: typeof PlanifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes': {
      id: '/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof DemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declarer': {
      id: '/declarer'
      path: '/declarer'
      fullPath: '/declarer'
      preLoaderRoute: typeof DeclarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/': {
      id: '/rh/'
      path: '/rh'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/speciaux': {
      id: '/rh/speciaux'
      path: '/rh/speciaux'
      fullPath: '/rh/speciaux'
      preLoaderRoute: typeof RhSpeciauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/soldes-cp': {
      id: '/rh/soldes-cp'
      path: '/rh/soldes-cp'
      fullPath: '/rh/soldes-cp'
      preLoaderRoute: typeof RhSoldesCpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/profil': {
      id: '/rh/profil'
      path: '/rh/profil'
      fullPath: '/rh/profil'
      preLoaderRoute: typeof RhProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/passif': {
      id: '/rh/passif'
      path: '/rh/passif'
      fullPath: '/rh/passif'
      preLoaderRoute: typeof RhPassifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/parametres': {
      id: '/rh/parametres'
      path: '/rh/parametres'
      fullPath: '/rh/parametres'
      preLoaderRoute: typeof RhParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/hierarchie': {
      id: '/rh/hierarchie'
      path: '/rh/hierarchie'
      fullPath: '/rh/hierarchie'
      preLoaderRoute: typeof RhHierarchieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/global': {
      id: '/rh/global'
      path: '/rh/global'
      fullPath: '/rh/global'
      preLoaderRoute: typeof RhGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/exports': {
      id: '/rh/exports'
      path: '/rh/exports'
      fullPath: '/rh/exports'
      preLoaderRoute: typeof RhExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/enfants': {
      id: '/rh/enfants'
      path: '/rh/enfants'
      fullPath: '/rh/enfants'
      preLoaderRoute: typeof RhEnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/employes': {
      id: '/rh/employes'
      path: '/rh/employes'
      fullPath: '/rh/employes'
      preLoaderRoute: typeof RhEmployesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/demandes-conges': {
      id: '/rh/demandes-conges'
      path: '/rh/demandes-conges'
      fullPath: '/rh/demandes-conges'
      preLoaderRoute: typeof RhDemandesCongesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/audit': {
      id: '/rh/audit'
      path: '/rh/audit'
      fullPath: '/rh/audit'
      preLoaderRoute: typeof RhAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/alertes': {
      id: '/rh/alertes'
      path: '/rh/alertes'
      fullPath: '/rh/alertes'
      preLoaderRoute: typeof RhAlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/profil': {
      id: '/manager/profil'
      path: '/manager/profil'
      fullPath: '/manager/profil'
      preLoaderRoute: typeof ManagerProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/planning': {
      id: '/manager/planning'
      path: '/manager/planning'
      fullPath: '/manager/planning'
      preLoaderRoute: typeof ManagerPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/parametres': {
      id: '/manager/parametres'
      path: '/manager/parametres'
      fullPath: '/manager/parametres'
      preLoaderRoute: typeof ManagerParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/historique': {
      id: '/manager/historique'
      path: '/manager/historique'
      fullPath: '/manager/historique'
      preLoaderRoute: typeof ManagerHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/demandes': {
      id: '/manager/demandes'
      path: '/manager/demandes'
      fullPath: '/manager/demandes'
      preLoaderRoute: typeof ManagerDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/conflits': {
      id: '/manager/conflits'
      path: '/manager/conflits'
      fullPath: '/manager/conflits'
      preLoaderRoute: typeof ManagerConflitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/calendrier': {
      id: '/manager/calendrier'
      path: '/manager/calendrier'
      fullPath: '/manager/calendrier'
      preLoaderRoute: typeof ManagerCalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/admin/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feries': {
      id: '/admin/feries'
      path: '/admin/feries'
      fullPath: '/admin/feries'
      preLoaderRoute: typeof AdminFeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departements': {
      id: '/admin/departements'
      path: '/admin/departements'
      fullPath: '/admin/departements'
      preLoaderRoute: typeof AdminDepartementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  DeclarerRoute: DeclarerRoute,
  DemandesRoute: DemandesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoriqueRoute: HistoriqueRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  PlanifierRoute: PlanifierRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SoldeRoute: SoldeRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AdminDepartementsRoute: AdminDepartementsRoute,
  AdminFeriesRoute: AdminFeriesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  ManagerCalendrierRoute: ManagerCalendrierRoute,
  ManagerConflitsRoute: ManagerConflitsRoute,
  ManagerDemandesRoute: ManagerDemandesRoute,
  ManagerHistoriqueRoute: ManagerHistoriqueRoute,
  ManagerParametresRoute: ManagerParametresRoute,
  ManagerPlanningRoute: ManagerPlanningRoute,
  ManagerProfilRoute: ManagerProfilRoute,
  RhAlertesRoute: RhAlertesRoute,
  RhAuditRoute: RhAuditRoute,
  RhDemandesCongesRoute: RhDemandesCongesRoute,
  RhEmployesRoute: RhEmployesRoute,
  RhEnfantsRoute: RhEnfantsRoute,
  RhExportsRoute: RhExportsRoute,
  RhGlobalRoute: RhGlobalRoute,
  RhHierarchieRoute: RhHierarchieRoute,
  RhParametresRoute: RhParametresRoute,
  RhPassifRoute: RhPassifRoute,
  RhProfilRoute: RhProfilRoute,
  RhSoldesCpRoute: RhSoldesCpRoute,
  RhSpeciauxRoute: RhSpeciauxRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  RhIndexRoute: RhIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
